<?php
require __DIR__ . '/includes/bootstrap.php';
$services = db()->query("SELECT * FROM services WHERE active=1 ORDER BY id DESC")->fetchAll();
$packages = db()->query("SELECT * FROM packages WHERE active=1 AND featured=1 ORDER BY id DESC LIMIT 3")->fetchAll();
$success = flash('success'); $error=flash('error'); $wa=app_config()['whatsapp'];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PG Estética Facial e Corporal</title><meta name="description" content="Estética facial, corporal e massoterapia com agenda online, pacotes e atendimento personalizado."><link rel="stylesheet" href="assets/css/style.css"></head><body>
<div class="topbar">Relaxe • Cuide-se • Renove • Seu bem-estar</div>
<header><div class="container"><nav><a class="brand" href="#inicio"><img src="assets/img/logo.jpeg" alt="PG Estética"><span>PG Estética</span></a><div class="navlinks"><a href="#servicos">Serviços</a><a href="packages.php">Pacotes</a><a href="#sobre">Sobre</a><a href="#agendamento">Agendamento</a><a class="btn btn-primary" href="#agendamento">Agendar horário</a></div></nav></div></header>
<main id="inicio"><section class="hero"><div class="container hero-grid"><div><div class="eyebrow">Estética facial • corporal • massoterapia</div><h1>Seu momento de cuidado, beleza e bem-estar.</h1><p>Protocolos personalizados, agendamento online e acompanhamento do seu histórico em um ambiente acolhedor.</p><div class="hero-actions"><a class="btn btn-primary" href="#agendamento">Ver horários disponíveis</a><a class="btn btn-outline" href="packages.php">Conhecer pacotes</a></div><div class="trust-row"><span>✓ Agenda online</span><span>✓ Confirmação por WhatsApp</span><span>✓ Pagamento Mercado Pago</span></div></div><div class="hero-card"><img src="assets/img/logo.jpeg" alt="Identidade visual PG Estética"></div></div></section>
<section id="servicos"><div class="container"><div class="section-title"><span class="eyebrow">Cuidados pensados para você</span><h2>Nossos serviços</h2><p>Escolha o procedimento e consulte os horários realmente disponíveis na agenda.</p></div><div class="grid"><?php foreach($services as $s): ?><article class="card"><div class="eyebrow"><?= e($s['category']) ?></div><h3><?= e($s['name']) ?></h3><p><?= e($s['description']) ?></p><div class="price"><?= money((float)$s['price']) ?> · <?= (int)$s['duration_minutes'] ?> min</div><a class="text-link" href="#agendamento" data-service="<?= (int)$s['id'] ?>">Agendar este serviço →</a></article><?php endforeach; ?></div></div></section>
<?php if($packages): ?><section class="soft"><div class="container"><div class="section-title"><span class="eyebrow">economia + continuidade</span><h2>Pacotes em destaque</h2></div><div class="grid"><?php foreach($packages as $p): ?><article class="card package-highlight"><span class="badge">Pacote</span><h3><?= e($p['name']) ?></h3><p><?= e($p['description']) ?></p><div class="price"><?= money((float)$p['price']) ?></div><a class="btn btn-outline" href="packages.php">Ver pacote</a></article><?php endforeach; ?></div></div></section><?php endif; ?>
<section id="sobre"><div class="container about"><div class="logo-wrap"><img src="assets/img/logo.jpeg" alt="PG Estética Facial e Corporal"></div><div><span class="eyebrow">Aqui, você é a prioridade</span><h2 class="display-title">Uma experiência de cuidado do primeiro contato ao pós-atendimento.</h2><p>A plataforma organiza agenda, ficha de anamnese, histórico de procedimentos e acompanhamento fotográfico para dar mais continuidade ao atendimento.</p><div class="values"><div class="value"><strong>Agenda inteligente</strong><br><span class="muted">Horários calculados conforme duração e bloqueios.</span></div><div class="value"><strong>Prontuário organizado</strong><br><span class="muted">Anamnese e histórico em um só lugar.</span></div><div class="value"><strong>Pacotes e pagamentos</strong><br><span class="muted">Compra online via Mercado Pago.</span></div><div class="value"><strong>Contato rápido</strong><br><span class="muted">Confirmações e lembretes por WhatsApp.</span></div></div></div></div></section>
<section id="agendamento" class="soft"><div class="container booking"><div><span class="eyebrow">Agendamento online</span><h2 class="display-title">Escolha um horário disponível.</h2><p>Selecione o serviço e a data. O sistema mostra apenas horários compatíveis com a jornada da clínica, duração do procedimento e outros agendamentos.</p><p class="muted small">Após solicitar, você recebe um link de confirmação. A equipe também pode acompanhar tudo pelo painel administrativo.</p><a class="btn btn-outline" target="_blank" href="https://wa.me/<?= e($wa) ?>">Falar no WhatsApp</a></div><div class="form-card"><?php if($success): ?><div class="notice"><?= e($success) ?></div><?php endif; ?><?php if($error): ?><div class="notice error"><?= e($error) ?></div><?php endif; ?><form method="post" action="actions/booking_create.php"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><label>Nome</label><input name="name" required maxlength="120"><div class="row"><div><label>WhatsApp</label><input name="phone" required maxlength="30" placeholder="(82) 99999-9999"></div><div><label>E-mail</label><input type="email" name="email" maxlength="150"></div></div><label>Serviço</label><select id="service_id" name="service_id" required><option value="">Selecione</option><?php foreach($services as $s): ?><option value="<?= (int)$s['id'] ?>"><?= e($s['name']) ?> · <?= money((float)$s['price']) ?></option><?php endforeach; ?></select><label>Data</label><input id="appointment_date" type="date" name="appointment_date" required min="<?= date('Y-m-d') ?>"><label>Horário disponível</label><select id="appointment_time" name="appointment_time" required disabled><option value="">Selecione serviço e data</option></select><div id="slots_hint" class="small muted"></div><label>Observações</label><textarea name="notes" maxlength="1000" placeholder="Conte brevemente o que você procura."></textarea><button class="btn btn-primary full" type="submit">Solicitar e receber confirmação</button></form></div></div></section>
</main><footer id="contato"><div class="container footer-grid"><div><h3>PG Estética Facial e Corporal</h3><p class="muted">Massoterapia • estética facial • estética corporal</p><p class="small">Relaxe. Cuide-se. Renove. Seu bem-estar.</p></div><div><strong>Atendimento</strong><p class="muted small">Segunda a sábado<br>Horários sob agendamento</p></div><div><strong>Links</strong><p><a href="packages.php">Pacotes</a><br><a href="admin/login.php">Área administrativa</a></p></div></div></footer>
<script>
const service=document.getElementById('service_id'),dateEl=document.getElementById('appointment_date'),timeEl=document.getElementById('appointment_time'),hint=document.getElementById('slots_hint');
async function loadSlots(){const s=service.value,d=dateEl.value;timeEl.innerHTML='<option>Carregando...</option>';timeEl.disabled=true;hint.textContent='';if(!s||!d){timeEl.innerHTML='<option value="">Selecione serviço e data</option>';return;}try{const r=await fetch(`actions/availability.php?service_id=${encodeURIComponent(s)}&date=${encodeURIComponent(d)}`);const data=await r.json();timeEl.innerHTML='<option value="">Selecione um horário</option>'+data.slots.map(x=>`<option value="${x}">${x}</option>`).join('');timeEl.disabled=data.slots.length===0;hint.textContent=data.slots.length?`${data.slots.length} horário(s) disponível(is).`:'Não há horários livres nesta data.';}catch(e){timeEl.innerHTML='<option value="">Erro ao consultar agenda</option>';hint.textContent='Tente novamente.';}}
service.addEventListener('change',loadSlots);dateEl.addEventListener('change',loadSlots);document.querySelectorAll('[data-service]').forEach(a=>a.addEventListener('click',()=>{service.value=a.dataset.service;setTimeout(()=>service.focus(),300);}));
</script></body></html>
