<?php require __DIR__.'/../includes/bootstrap.php'; admin_required();
$today=date('Y-m-d');$month=date('Y-m');
$stats=[];$stats['today']=(int)db()->query("SELECT COUNT(*) FROM appointments WHERE appointment_date=CURDATE() AND status<>'cancelado'")->fetchColumn();
$stats['clients']=(int)db()->query('SELECT COUNT(*) FROM clients')->fetchColumn();
$stats['pending']=(int)db()->query("SELECT COUNT(*) FROM appointments WHERE status='pendente'")->fetchColumn();
$stats['revenue']=(float)db()->query("SELECT COALESCE(SUM(amount),0) FROM finance_transactions WHERE type='receita' AND status='pago' AND DATE_FORMAT(paid_date,'%Y-%m')=DATE_FORMAT(CURDATE(),'%Y-%m')")->fetchColumn();
$stats['expense']=(float)db()->query("SELECT COALESCE(SUM(amount),0) FROM finance_transactions WHERE type='despesa' AND status='pago' AND DATE_FORMAT(paid_date,'%Y-%m')=DATE_FORMAT(CURDATE(),'%Y-%m')")->fetchColumn();
$todayItems=db()->query("SELECT a.*,c.name client_name,c.phone,s.name service_name FROM appointments a JOIN clients c ON c.id=a.client_id JOIN services s ON s.id=a.service_id WHERE a.appointment_date=CURDATE() ORDER BY a.appointment_time")->fetchAll();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | PG Estética</title><link rel="stylesheet" href="../assets/css/style.css"></head><body class="admin-shell"><?php include '_nav.php'; ?><section><div class="container"><div class="admin-heading"><div><span class="eyebrow">visão geral</span><h1>Olá, <?= e($_SESSION['admin_name']) ?></h1></div><a class="btn btn-primary" href="appointments.php">Abrir agenda</a></div><div class="stat-grid stat-grid-5"><div class="stat"><span>Hoje</span><strong><?= $stats['today'] ?></strong><small>atendimentos</small></div><div class="stat"><span>Clientes</span><strong><?= $stats['clients'] ?></strong></div><div class="stat"><span>A confirmar</span><strong><?= $stats['pending'] ?></strong></div><div class="stat"><span>Receitas no mês</span><strong class="money-stat"><?= money($stats['revenue']) ?></strong></div><div class="stat"><span>Resultado do mês</span><strong class="money-stat"><?= money($stats['revenue']-$stats['expense']) ?></strong></div></div><div class="panel"><div class="panel-head"><h2>Agenda de hoje</h2><a href="appointments.php">Ver agenda completa →</a></div><?php if(!$todayItems): ?><p class="muted">Nenhum atendimento para hoje.</p><?php else: ?><div class="table-wrap flat"><table><thead><tr><th>Horário</th><th>Cliente</th><th>Procedimento</th><th>Status</th></tr></thead><tbody><?php foreach($todayItems as $a): ?><tr><td><strong><?= substr($a['appointment_time'],0,5) ?></strong></td><td><a href="client.php?id=<?= (int)$a['client_id'] ?>"><?= e($a['client_name']) ?></a><br><span class="small muted"><?= e($a['phone']) ?></span></td><td><?= e($a['service_name']) ?></td><td><span class="badge status-<?= e($a['status']) ?>"><?= e($a['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></section></body></html>
