<?php require __DIR__.'/../includes/bootstrap.php'; admin_required();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $action=$_POST['action']??'save';
 if($action==='delete'){ $id=(int)$_POST['id']; db()->prepare('UPDATE services SET active=0 WHERE id=?')->execute([$id]); header('Location: services.php'); exit; }
 $id=(int)($_POST['id']??0); $name=trim($_POST['name']??''); $category=trim($_POST['category']??''); $description=trim($_POST['description']??''); $price=(float)str_replace(',','.',$_POST['price']??0); $duration=(int)($_POST['duration_minutes']??60);
 if($id){db()->prepare('UPDATE services SET name=?,category=?,description=?,price=?,duration_minutes=?,active=1 WHERE id=?')->execute([$name,$category,$description,$price,$duration,$id]);}
 else{db()->prepare('INSERT INTO services(name,category,description,price,duration_minutes,active) VALUES(?,?,?,?,?,1)')->execute([$name,$category,$description,$price,$duration]);}
 header('Location: services.php'); exit;
}
$edit=null;if(isset($_GET['edit'])){$st=db()->prepare('SELECT * FROM services WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$services=db()->query('SELECT * FROM services ORDER BY active DESC,id DESC')->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Serviços | PG Estética</title><link rel="stylesheet" href="../assets/css/style.css"></head><body class="admin-shell"><?php include '_nav.php'; ?><section><div class="container"><div class="booking"><div class="form-card"><h2><?= $edit?'Editar':'Novo' ?> serviço</h2><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Nome</label><input name="name" required value="<?= e($edit['name']??'') ?>"><label>Categoria</label><input name="category" required value="<?= e($edit['category']??'') ?>" placeholder="Facial, Corporal, Massoterapia"><label>Descrição</label><textarea name="description"><?= e($edit['description']??'') ?></textarea><div class="row"><div><label>Preço (R$)</label><input type="number" step="0.01" min="0" name="price" required value="<?= e(isset($edit['price'])?(string)$edit['price']:'') ?>"></div><div><label>Duração (min)</label><input type="number" min="10" step="5" name="duration_minutes" required value="<?= (int)($edit['duration_minutes']??60) ?>"></div></div><button class="btn btn-primary" style="margin-top:1rem">Salvar</button></form></div><div><h2>Serviços cadastrados</h2><div class="table-wrap"><table><thead><tr><th>Serviço</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($services as $s): ?><tr><td><strong><?= e($s['name']) ?></strong><br><span class="small muted"><?= e($s['category']) ?></span></td><td>R$ <?= number_format((float)$s['price'],2,',','.') ?></td><td><span class="badge"><?= $s['active']?'Ativo':'Inativo' ?></span></td><td><a href="?edit=<?= (int)$s['id'] ?>">Editar</a><?php if($s['active']): ?> · <form method="post" style="display:inline" onsubmit="return confirm('Desativar este serviço?')"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><button type="submit" style="border:0;background:none;color:#852d24;cursor:pointer">Desativar</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div></section></body></html>
